import { Pantry } from './types';

export const PANTRIES: Pantry[] = [
  {
    id: '1',
    name: 'Greater Chicago Food Depository',
    address: '4100 W Ann Lurie Pl',
    city: 'Chicago',
    state: 'IL',
    zip: '60632',
    phone: '(773) 247-3663',
    email: 'info@gcfd.org',
    lat: 41.8178,
    lng: -87.731,
    hours: 'Mon–Fri 8am–5pm',
    description: "Chicago's food bank serving over 700 pantries across Cook County.",
  },
  {
    id: '2',
    name: 'Logan Square Food Pantry',
    address: '2200 N California Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    phone: '(773) 342-5600',
    email: 'contact@logansquarepantry.org',
    lat: 41.9208,
    lng: -87.6978,
    hours: 'Tue & Thu 10am–2pm',
    description: 'Serving the Logan Square and Humboldt Park neighborhoods.',
  },
  {
    id: '3',
    name: 'Lakeview Pantry',
    address: '3831 N Broadway',
    city: 'Chicago',
    state: 'IL',
    zip: '60613',
    phone: '(773) 935-1600',
    email: 'help@lakeviewpantry.org',
    lat: 41.9504,
    lng: -87.6458,
    hours: 'Mon–Sat 9am–3pm',
    description: 'Providing food assistance and wellness programs to Lakeview residents.',
  },
  {
    id: '4',
    name: 'South Side Community Food Hub',
    address: '6335 S Cottage Grove Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60637',
    phone: '(773) 288-0400',
    email: 'info@southsidefoodhub.org',
    lat: 41.7797,
    lng: -87.6065,
    hours: 'Wed & Fri 11am–4pm',
    description: 'Serving the Woodlawn and South Shore communities.',
  },
  {
    id: '5',
    name: 'Near North Food Pantry',
    address: '845 N Orleans St',
    city: 'Chicago',
    state: 'IL',
    zip: '60610',
    phone: '(312) 266-5700',
    email: 'pantry@nearnorth.org',
    lat: 41.8973,
    lng: -87.6368,
    hours: 'Mon, Wed, Fri 9am–12pm',
    description: 'Providing emergency food assistance in the Near North community.',
  },
  {
    id: '6',
    name: 'Pilsen Community Pantry',
    address: '1925 S Blue Island Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60608',
    phone: '(312) 226-4700',
    email: 'info@pilsenpantry.org',
    lat: 41.8554,
    lng: -87.6601,
    hours: 'Tue & Thu 1pm–5pm, Sat 10am–1pm',
    description: 'Bilingual (English/Spanish) food assistance serving the Pilsen neighborhood.',
  },
  {
    id: '7',
    name: 'Austin Community Food Bank',
    address: '5104 W Chicago Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60651',
    phone: '(773) 854-2000',
    email: 'austin@austinfoodbank.org',
    lat: 41.8956,
    lng: -87.7582,
    hours: 'Mon–Fri 10am–3pm',
    description: 'Serving the Austin community with fresh produce and pantry staples.',
  },
  {
    id: '8',
    name: 'Uptown United Pantry',
    address: '4650 N Racine Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60640',
    phone: '(773) 561-8500',
    email: 'uptown@uptownunited.org',
    lat: 41.9659,
    lng: -87.6589,
    hours: 'Mon, Wed, Fri 10am–2pm',
    description: 'Providing food and social services for Uptown residents.',
  },
];
